region                = "us-east-1"
lambda_code_bucket    = "lambda-code-bucket-name"
terraform_state_bucket = "terraform-state-bucket-name"
lambda_code_path      = "/path/to/lambda/code.zip"
lambda_function_name  = "LambdaFunction"